exports.FULLSCREEN_BREAK = "FULLSCREEN_BREAK";
exports.CLOSE_BREAK = "CLOSE_BREAK";
exports.NOTIFY_BREAK_STARTING = "NOTIFY_BREAK_STARTING";
exports.SNOOZE = "SNOOZE";
exports.TRIGGER_BREAK_END_SOUND = "TRIGGER_BREAK_END_SOUND";
exports.PLAY_BREAK_END_SOUND = "PLAY_BREAK_END_SOUND";

exports.APP_VERSION = "0.0.1";
exports.COPYRIGHT = "Copyright © 2021 Jared Tong.";
